spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mana_db?serverTimezone=UTC&characterEncoding=UTF-8"
    username: "root"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
      enabled: true
  jpa:
    database:
    hibernate:
      ddl_auto: none #validate로 검증하려고 했는데, jpa2.1부터 지원안함
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
        format_sql: true
        show_sql: true #sys.out으로 sql 로그 남겨줌.
    database-platform: org.hibernate.dialect.MySQL8Dialect