pipeline {
    agent any

    stages {
        stage("Set Variable") {
            steps {
                script {
                    IMAGE_NAME = "sh80165/manamana-frontend"
                    IMAGE_STORAGE = "https://registry.hub.docker.com"
                    IMAGE_STORAGE_CREDENTIAL = "docker-auth"
                    NODE_BUILD_PATH = "./build"
                    APPLICATION_ENV_PATH = "/var/jenkins_home/workspace"
                    ESLINTIGNORE_PATH = "/var/jenkins_home/workspace/manamana-frontend"
                    CONTAINER_NAME = "manamana-fronted"
                    PROJECT_DIR = "frontend"
                    DOCKER_FILE_PATH = "frontend/"
                }
            }
        }

        stage("Node install & build") {
            steps {
                dir("${ESLINTIGNORE_PATH}"){
                    sh "pwd"
                    sh "cp -f eslintignore frontend/eslintignore"
                }
            }
        }
        stage("env copy") {
            steps {
                dir("${APPLICATION_YML_PATH}"){
                    sh "pwd"
                    sh "cp -f fronted_env/.env manamana-frontend/frontend/.env"
                }
            }
        }

        stage("Clean Container&Image") {
            steps {
                script{
                    // //컨테이너 확인 후 정지
                    sh "docker ps -f name=${CONTAINER_NAME} -q | xargs --no-run-if-empty docker container stop"

                    // //컨테이너 삭제
                    sh "docker container ls -a -f name=${CONTAINER_NAME} -q | xargs -r docker container rm"

                    //기존 이미지 삭제
                    sh "docker images ${IMAGE_NAME} -q | xargs -r docker rmi -f"
                }
            }
        }

        stage("Build Container Image") {
            steps {
                dir("${DOCKER_FILE_PATH}"){
                    script {
                        sh "pwd" 
                        image = docker.build("${IMAGE_NAME}")
                    }
                }
                
            }
        }

        stage("Push Container Image") {
            steps {
                script {
                    docker.withRegistry("", "${IMAGE_STORAGE_CREDENTIAL}") {
                        image.push("latest")
                    }
                }
            }
        }

        stage("Server Run") {
            steps {
                script{

                    //컨테이너 확인
                    sh "docker ps -a"

                    // 이미지 확인
                    sh "docker images"

                    // 최신 이미지 RUN
                    sh "docker run -d --name ${CONTAINER_NAME} -p 3000:3000 ${IMAGE_NAME}:latest"

                    // 컨테이너 확인 - 로그 확인용
                    sh "docker ps -a"
                }
            }
        }
    }
}