pipeline {
    agent any
    stages {
        stage("Set Variable") {
            steps {
                script {
                    IMAGE_NAME = "sh80165/crawling"
                    IMAGE_STORAGE = "https://registry.hub.docker.com"
                    IMAGE_STORAGE_CREDENTIAL = "docker-auth"
                    APPLICATION_YML_PATH = "/var/jenkins_home/workspace"
                    CONTAINER_NAME = "crawling"
                    PROJECT_DIR = "crawling/crawling/"
                    DOCKER_FILE_PATH = "crawling/"
                    DOCKER_COMPOSE_PATH = "/var/jenkins_home/workspace/crawling/"
                }
            }
        }
        stage("Copy user-env"){
            steps{
                dir("${APPLICATION_YML_PATH}"){
                    sh "pwd"
                    sh "cp -r -f crawling-env ${PROJECT_DIR}"
                }
            }
        }

        stage("Build Container Image") {
            steps {
                dir("${DOCKER_FILE_PATH}"){
                    script {
                        image = docker.build("${IMAGE_NAME}")
                    }   
                }
                
            }
        }

        stage("Push Container Image") {
            steps {
                script {
                    docker.withRegistry("", "${IMAGE_STORAGE_CREDENTIAL}") {
                        image.push("latest")
                    }
                }
            }
        }

        stage("Server Run") {
            steps {
                script {

                    // 도커 컴포즈 down
                    sh "docker compose down"

                    //컨테이너 확인
                    sh "docker ps -a"
                    
                    // 최신 이미지 PULL
                    sh "docker pull ${IMAGE_NAME}:latest"

                    // 이미지 확인
                    sh "docker images"

                    // 도커 컴포즈 start
                    sh "docker compose up -d"

                    // 컨테이너 확인 - 로그 확인용
                    sh "docker ps -a"

                }
            }
        }
    }
}
